// export const data = {
//   status: "OK",
//   request_id: "ce184279-8b01-4373-9db4-a6ed4b7129d7",
//   parameters: {
//     query: "react developer",
//     page: 1,
//     num_pages: 1,
//   },
//   data: [
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//     {
//       employer_name: "SynergisticIT",
//       employer_logo:
//         "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
//       employer_website: null,
//       employer_company_type: null,
//       job_publisher: "LinkedIn",
//       job_id: "BFy4_X5fiosAAAAAAAAAAA==",
//       job_employment_type: "CONTRACTOR",
//       job_title: "Java React Developer (Remote)",
//       job_apply_link:
//         "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
//       job_apply_is_direct: false,
//       job_apply_quality_score: 0.5724,
//       job_description:
//         "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
//       job_is_remote: true,
//       job_posted_at_timestamp: 1681794552,
//       job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
//       job_city: "Oklahoma City",
//       job_state: "OK",
//       job_country: "US",
//       job_latitude: 35.46756,
//       job_longitude: -97.516426,
//       job_benefits: null,
//       job_google_link:
//         "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
//       job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
//       job_offer_expiration_timestamp: 1684386552,
//       job_required_experience: "",
//       job_required_skills: null,
//       job_experience_in_place_of_education: false,
//       job_min_salary: null,
//       job_max_salary: null,
//       job_salary_currency: null,
//       job_salary_period: null,
//       job_job_title: null,
//       job_posting_language: "en",
//       job_onet_soc: "15113400",
//       job_onet_job_zone: "3",
//     },
//   ],
// };

export const data = [
  {
    employer_name: "SynergisticIT",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "BFy4_X5fiosAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Java React Developer (Remote)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5724,
    job_description:
      "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
    job_is_remote: true,
    job_posted_at_timestamp: 1681794552,
    job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
    job_city: "Oklahoma City",
    job_state: "OK",
    job_country: "US",
    job_latitude: 35.46756,
    job_longitude: -97.516426,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
    job_offer_expiration_timestamp: 1684386552,
    job_required_experience: "",
    job_required_skills: null,
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "SynergisticIT",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "BFy4_X5fiosAAAAAAAAAAA==3",
    job_employment_type: "CONTRACTOR",
    job_title: "Java React Developer (Remote)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5724,
    job_description:
      "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
    job_is_remote: true,
    job_posted_at_timestamp: 1681794552,
    job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
    job_city: "Oklahoma City",
    job_state: "OK",
    job_country: "US",
    job_latitude: 35.46756,
    job_longitude: -97.516426,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
    job_offer_expiration_timestamp: 1684386552,
    job_required_experience: "",
    job_required_skills: null,
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "SynergisticIT",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "BFy4_X5fiosAAAAAAAAAAA=1431064",
    job_employment_type: "CONTRACTOR",
    job_title: "Java React Developer (Remote)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5724,
    job_description:
      "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
    job_is_remote: true,
    job_posted_at_timestamp: 1681794552,
    job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
    job_city: "Oklahoma City",
    job_state: "OK",
    job_country: "US",
    job_latitude: 35.46756,
    job_longitude: -97.516426,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
    job_offer_expiration_timestamp: 1684386552,
    job_required_experience: "",
    job_required_skills: null,
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "SynergisticIT",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-UrAK1LCetSvno8PT3nMB4vJV4VdEEPN7PrgC&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "BFy4_X5fiosAAAAAAAAAAA=143106",
    job_employment_type: "CONTRACTOR",
    job_title: "Java React Developer (Remote)",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/java-react-developer-remote-at-synergisticit-3567935672",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5724,
    job_description:
      "SYNERGISTICIT wants every candidate to know that the Job Market is Challenging and to stand out, you need to have exceptional skills and technologies and that's where we come in to make sure you get the attention which you need SynergisticIT understands the complex nature of the job market and how difficult it can be to secure a position, especially for fresh graduates. Therefore, we assist and help tech-savvies to convert their passions into professions. We go above and beyond to keep you working in your niche. As we focus on long-term success, we provide complete career development solutions. From job search to upskilling portfolio and interview preparation, we can guide you at every step of your career. SynergisticIT spares no efforts to connect you with a large network of tech giants, including Google, Apple, PayPal, Dell, Cisco, Client, etc. Presently, we are actively looking for Java React Developer (Remote) with a driven mindset. Get the right opportunity and gain experience in building web-centric solutions on Java. Who Should Apply : Recent Computer science/Engineering /Mathematics/Statistics or Science Graduates or anyone looking to make their career in IT Industry We also assist in filing for STEM extension and H1b and Green card filing. Candidates who are serious about their future in the IT Industry and have set big goals for themselves. Candidates having difficulty in finding jobs or cracking interviews or who wants to improve their skill portfolio. We also offer Skill Enhancement Programs if the candidates are missing skills or experience which our clients need with great outcomes Candidates can benefit from skill enhancement if they fall into the below categories. If they are qualified with enough skills then no need for skill enhancement Candidates Who Lack Experience Have had a break in careers Lack Technical Competency candidates who want to get employed and make a career in the Tech Industry Please Also Check The Below Links https://www.synergisticit.com/candidate-outcomes/ https://www.synergisticit.com/java-track/ https://www.synergisticit.com/data-science-track/ https://www.synergisticit.com/which-is-the-best-option-for-tech-job-seekers-staffing-companies-consulting-companies-bootcamps-or-synergisticit/ https://www.synergisticit.com/contact-us/ If the skills are not a match candidates can opt for Skill enhancement. Or their resume can be sent out to clients to see if responses are achievable REQUIRED SKILLS For Java/Software Programmers • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Core Java , javascript , C++ or software programming • Spring boot, Microservices and REST API's experience • Excellent written and verbal communication skills For data Science/Machine learning Required Skills • Bachelors degree or Masters degree in Computer Science, Computer Engineering, Electrical Engineering, Information Systems, IT • Highly motivated, self-learner, and technically inquisitive • Experience in programming language Java and understanding of the software development life cycle • Knowledge of Statistics, Python, data visualization tools • Excellent written and verbal communication skills Preferred skills: NLP, Text mining, Tableau, Time series analysis Technical skills are required by clients for selection even if its Junior or entry level position each additional Technical skill helps a candidate's resume to be picked by clients over other job seekers. Clients hire candidates with the right technical skills which they need and reject candidates who lack the required technical skills. No third party candidates or c2c candidates Please apply to the posting No phone calls please. Shortlisted candidates would be reached out",
    job_is_remote: true,
    job_posted_at_timestamp: 1681794552,
    job_posted_at_datetime_utc: "2023-04-18T05:09:12.000Z",
    job_city: "Oklahoma City",
    job_state: "OK",
    job_country: "US",
    job_latitude: 35.46756,
    job_longitude: -97.516426,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer&htidocid=BFy4_X5fiosAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-05-18T05:09:12.000Z",
    job_offer_expiration_timestamp: 1684386552,
    job_required_experience: "",
    job_required_skills: null,
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
];
